spring:
  application:
    name: statistics
  jpa:
    database: H2
    show-sql: false
    properties:
      hibernate:
       format_sql: true
    hibernate:      
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:got;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      indent-output: true
    
logging:
  level:
    ROOT: ERROR
    org.springframework.web: ERROR
    com.n26.codechallenge: INFO
  file:  /opt/n26_code_challenge/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"